language: go
go:
  - 1.9
env:
  global:
    - TEST_TIMEOUT_SCALE=40
cache:
  directories:
    - vendor
install:
  - make dependencies
script:
  - make lint
  - make test
after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
